### ISSUE TITLE
Ballett am falschen Tag

### ISSUE THREAD

**Issue by mbihn** [mschuma2/drupal-bgc-mobile-theme#1]
Für heute erscheint im Kalender noch Ballett (7-8 Jahre) - das ist aber erst morgen.  Da fehlt es dann.

In Drupal steht es korrekt für Donnerstag drin ... kann nichts seltsames daran entdecken.

**Comment by mschuma2** [comment]
This issue was moved to mschuma2/bgc_calendar_sync#22
